### ISSUE TITLE
SyntaxError when installing

### ISSUE THREAD

**Issue by terrytykuo** [brian-team/brian#6]
Hi, 

There's an error occurred when installing, (`pip install`) could you please help with that?
Full error report:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h1/r3wdlsgn3d95857wmhyt5gxm0000gn/T/pip-install-phjpxnk1/brian/setup.py", line 31
        except CCompilerError, ex:
                             ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h1/r3wdlsgn3d95857wmhyt5gxm0000gn/T/pip-install-phjpxnk1/brian/

```

**Comment by mstimberg** [comment]
Hi, please note that we are not developing Brian 1 any more, please consider using [Brian 2](http://brian2.readthedocs.io) instead. Brian 1 is not compatible with Python 3.x, I think this is why you are getting the error. Please either use Python 2.7, or switch to Brian 2 which supports both Python 2 and Python 3.

**Comment by sealpuppy** [comment]
Thanks! I will try Brian2.

**Comment by theUnspecified** [comment]
Hi, I am using python 2 and I am facing the same problem while installing using pip. My system is Ubuntu 18.04 and Python 2.7.

**Comment by mstimberg** [comment]
The error above should only occur under Python 3. Can you post your error message?

**Comment by theUnspecified** [comment]
It is solved, thanks for your response. Error message was same but i did some mistake. Thank you @mstimberg
